# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

language: cpp

python:
  - "2.7"
  - "3.4"

compiler:
    - g++

branches:
    only:
        - test_py2_and_py3_support
    
env:
    global:
        CXXFLAGS="-O3 -Wall -Wextra -Wno-unused-parameter -Wno-empty-body -Wno-format-security"
    matrix:
        # Python 2
        # Serial build and test
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR"
          TEST_SCRIPT=serial_regression.py
          PYTHON=python
        # Parallel build and test
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR"
          TEST_SCRIPT=parallel_regression.py
          PYTHON=python
        # Serial build and test for AD
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff"
          TEST_SCRIPT=serial_regression_AD.py
          PYTHON=python
        # Parallel build and test for AD
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff"
          TEST_SCRIPT=parallel_regression_AD.py
          PYTHON=python
          
        # Python 3
        # Serial build and test
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR"
          TEST_SCRIPT=serial_regression.py
          PYTHON=python3
          # Parallel build and test
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR"
          TEST_SCRIPT=parallel_regression.py
          PYTHON=python3
        # Serial build and test for AD
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff"
          TEST_SCRIPT=serial_regression_AD.py
          PYTHON=python3
        # Parallel build and test for AD
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff"
          TEST_SCRIPT=parallel_regression_AD.py
          PYTHON=python3


before_install:
    # install the necessary packages
    - sudo apt-get update -qq
    - sudo apt-get install -qq mpich2
    - sudo apt-get install -qq python-numpy python-scipy
    - sudo apt-get install -qq python3-numpy python3-scipy

install:
    - echo $TRAVIS_BUILD_DIR
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND
    - make -j 4
    - make install

    # Add environmental variables according to the configure step
    - export SU2_RUN=$TRAVIS_BUILD_DIR/bin
    - export SU2_HOME=$TRAVIS_BUILD_DIR
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN

before_script:
    # Get the test cases
    - git clone https://github.com/su2code/TestCases.git ./TestData
    - cd TestData/
    - git checkout develop
    # Go back to SU2 root and copy the test data into the folder structure
    - cd $TRAVIS_BUILD_DIR
    - cp -R ./TestData/* ./TestCases/
    # Enter the SU2/TestCases/ directory, which is now ready to run
    - cd TestCases/

script:
    # run the tests
    $PYTHON $TEST_SCRIPT

